"""Add administrative audit fields

Revision ID: 0f534fd40195
Revises: e7f0a1c2add3
Create Date: 2026-04-04 10:38:19.109635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0f534fd40195'
down_revision: Union[str, Sequence[str], None] = 'e7f0a1c2add3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_invites', sa.Column('revoked_by_user_id', sa.Integer(), nullable=True))
    op.add_column('admin_invites', sa.Column('revoked_reason', sa.String(length=500), nullable=True))
    op.drop_index(op.f('ix_admin_invites_status'), table_name='admin_invites')
    op.create_foreign_key(None, 'admin_invites', 'users', ['revoked_by_user_id'], ['id'])
    op.alter_column('elections', 'status',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.add_column('users', sa.Column('disabled_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('disabled_by_user_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('suspended_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('suspension_reason', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('last_login_ip', sa.String(length=64), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['disabled_by_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'last_login_ip')
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'suspension_reason')
    op.drop_column('users', 'suspended_at')
    op.drop_column('users', 'disabled_by_user_id')
    op.drop_column('users', 'disabled_at')
    op.alter_column('elections', 'status',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_constraint(None, 'admin_invites', type_='foreignkey')
    op.create_index(op.f('ix_admin_invites_status'), 'admin_invites', ['status'], unique=False)
    op.drop_column('admin_invites', 'revoked_reason')
    op.drop_column('admin_invites', 'revoked_by_user_id')
    # ### end Alembic commands ###
