"""add_citizenship_fields_to_users

Revision ID: 502738a54e5b
Revises: 67fb4b013743
Create Date: 2026-03-02 23:56:17.852883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '502738a54e5b'
down_revision: Union[str, Sequence[str], None] = '67fb4b013743'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('citizenship_no_raw', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('citizenship_no_normalized', sa.String(length=16), nullable=True))
    op.add_column('users', sa.Column('status', sa.String(length=20), nullable=False))
    op.create_index(op.f('ix_users_citizenship_no_normalized'), 'users', ['citizenship_no_normalized'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_citizenship_no_normalized'), table_name='users')
    op.drop_column('users', 'status')
    op.drop_column('users', 'citizenship_no_normalized')
    op.drop_column('users', 'citizenship_no_raw')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###
