"""add pending_voter_registrations table

Revision ID: 6a8b4ba9c683
Revises: b2c3d4e5f6a8
Create Date: 2026-04-08 18:04:12.714174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a8b4ba9c683'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_voter_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('citizenship_no_raw', sa.String(length=50), nullable=False),
    sa.Column('citizenship_no_normalized', sa.String(length=16), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('email_token_hash', sa.String(length=64), nullable=True),
    sa.Column('email_token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('citizenship_image_path', sa.String(length=500), nullable=True),
    sa.Column('document_uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('face_image_path', sa.String(length=500), nullable=True),
    sa.Column('face_uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('converted_user_id', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['converted_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_voter_registrations_citizenship_no_normalized'), 'pending_voter_registrations', ['citizenship_no_normalized'], unique=True)
    op.create_index(op.f('ix_pending_voter_registrations_email'), 'pending_voter_registrations', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pending_voter_registrations_email'), table_name='pending_voter_registrations')
    op.drop_index(op.f('ix_pending_voter_registrations_citizenship_no_normalized'), table_name='pending_voter_registrations')
    op.drop_table('pending_voter_registrations')
    # ### end Alembic commands ###
