"""add_citizenship_upload_fields

Revision ID: c2a4260af43c
Revises: b2c3d4e5f6a7
Create Date: 2026-03-06 10:45:29.267093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2a4260af43c'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('citizenship_image_path', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('document_uploaded_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'document_uploaded_at')
    op.drop_column('users', 'citizenship_image_path')
    # ### end Alembic commands ###
