"""add_totp_fields_to_users

Revision ID: de30b9dc25e3
Revises: c2ee88ae5595
Create Date: 2026-03-04 21:55:20.102219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de30b9dc25e3'
down_revision: Union[str, Sequence[str], None] = 'c2ee88ae5595'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('totp_secret', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('totp_enabled_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'totp_enabled_at')
    op.drop_column('users', 'totp_secret')
    # ### end Alembic commands ###
